version: '3.8'


services:
  app:
    container_name: bot
    tty: true
    build: ./
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    restart: always
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  app:
  postgres_data:

